# Конфигурация для A/B тестирования

# Режим работы: "single" - один сервис, "dual" - два сервиса, "triple" - три сервиса
mode: triple

# Конфигурация сервисов
services:
  service_a:
    url: ...  
    weight: 0.33
  service_b:
    url: ...
    weight: 0.33
  service_c:
    url: ...
    weight: 0.33

# Таймаут для запросов к сервисам (в секундах)
timeout: 35

# Если True, в случае недоступности одного сервиса перенаправляет на другой
fallback_enabled: true 